name: "v2ray-放牧的风"

on:
  workflow_dispatch:
  schedule:
    - cron: "10 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
         ref: master

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run sign
        run: |
          pip install -r requirements.txt
          python3 v2fangmudefeng.py
        env:
            DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
            DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with: 
          branch: v2ray
          folder: v2ray
